module.exports = function() {
    return {
        products: [
            {id:1,
             name:"Veri Madenciliği Süreçleri Nelerdir?",
             price:1000,
             imageUrl:'1.jpg',
             category:'Veri Madenciliği'},
             { id:2, 
                name:"Veri Madenciliği Yöntemleri nelerdir?", 
                imageUrl:'2.jpg',
                category:'Veri Madenciliği' },
            { id:3, 
            name:"Veri Madenciliği Hangi Alanlarda kullanılır ?", 
            imageUrl:'3.jpg', 
            category:'Veri Madenciliği' },
            { id:4,
                 name:"TIP ve SAĞLIK HİZMETLERİNDE VERİ MADENCİLİĞİ KULLANIMI ve UYGULAMALARI",
                 imageUrl:'4.jpg',
                  description:'',
                  category:'Veri Madenciliğinde Tıp Yöntemleri' },
            { id:5, 
                name:"Tıbbi verilerin Yapısı", 
                imageUrl:'5.jpg', 
                description:'',
                category:'Veri Madenciliğinde Tıp Yöntemleri' },
                { id:6, 
                    name:"Hastane Bilgi Sistemlerinde Veri Madenciliği Uygulamaları", 
                    imageUrl:'6.jpg', 
                    description:'',
                    category:'Veri Madenciliğinde Tıp Yöntemleri' } ,
                    { id:7, 
                        name:"Kanser nedir ?", 
                        imageUrl:'7.jpg', 
                        description:'İnsan vücudundaki sağlıklı hücrelerin, kas ve sinir hücreleri hariç, bölünebilme yeteneği vardır. Hücreler, yenilenme ve yaralanan dokuların onarılması amacıyla bölünebilme yeteneklerini kullanırlar. Her hücrenin hayatı boyunca belli bir bölünebilme sayısı vardır. Sağlıklı bir hücre gerektiği yerde ve gerektiği kadar bölüneceğini bilir. Buna karşın kanser hücreleri, bu bilinci kaybedip kontrolsüz olarak bölünmeye baĢlayarak çoğalırlar. Bütün bu bilgilerden yola çıkarak kanser için aĢağıdaki tanımlamaları yapabiliriz, Kanser için en doğru tanımlamaları aĢağıdaki gibi açıklayabiliriz. Kanser, bir dokunun veya organın hücrelerinde sağlıksız bir değişme ortaya çıkıp bu hücrelerin denetimsiz çoğalmaya başlamasıyla meydana gelen hastalıkların tümü için kullanılan bir genel kavramdır. - Genellikle kontrolden çıkan hücrelerin hızlı ve sürekli çoğalmalarıdır. Vücudumuzun her organı birçok farklı hücre tiplerinden oluşmaktadır. Normal olarak bu hücreler vücut için gerekli olduğu şekilde belli bir düzen içinde büyüyerek bölünürler. Bu süreç bir düzen içinde yürür ve vücut sağlığının korunmasına yarar. Eğer, yeni hücrelere ihtiyaç olmadığı halde hücreler bölünmeye başlarsa, gereğinden fazla doku oluşmaya başlar. Bu fazlalık dokular tümör denen bir urun ortaya çıkmasına sebep olurlar. Böylece oluşan fazlalık doku iyi huylu veya kötü huylu olabilir. - Kötü huylu tümörlerdir; yani iyi huylu) tümörlerin aksine başka dokulara sızma ve yayılma özelliği gösterirler. ',
                        category:'Gögüs Kanseri Veri Seti Analizi'},
                        { id:8, 
                            name:"Göğüs Kanseri örnek uygulaması", 
                            imageUrl:'8.jpg', 
                            description:'Xcyt , 1990 yıllarının başında Amerika Madison Eyaleti Wisconsin Üniversitesi’nde temelleri atılan bir yazılım projesinin adıdır. Yazılım, meme kanserindeki iki önemli safha olan tanı (diagnosis) ve tahmin (prognosis) safhalarını gerçekleştirmeyi hedefleyerek bir proje olarak ortaya çıkmıştır. şekil 4.3‟de kanser riski taşıyan bir hastanın göğsünden alınan doku örneğinin mikroskop altında 63 defa büyütülmesi ile elde edilen görüntü verilmiştir. Bu görüntü kullanılarak kenar çıkarma ve merkez saptama algoritmaları ile Xcyt programına hücrelerin özelliklerinden dokunun genel şablonu çıkarttırılmaktadır. Xcyt programı ile şekil 4.4’de görüldüğü gibi önce verilen hücre topluluğu gri skalaya çevrilmiştir.',
                            category:'Gögüs Kanseri Veri Seti Analizi' } ,
                            { id:9, 
                                name:"Göğüs Kanseri Verileri Üzerinde Makine Öğrenmesi Yöntemlerinin Uygulanması", 
                                imageUrl:'9.jpg', 
                                description:'Kanser dünya genelinde pek çok insanın ölümüne sebep olan en önemli hastalıklardan biridir. Özellikle göğüs kanseri kadınlar arasında en çok rastlanan hastalıkların başında yer almaktadır. Bu sebeple kanser hastalığının teşhisi ile alakalı herhangi bir gelişme insanların sağlıklı bir yaşam sürmesi açısından oldukça önemlidir. Günümüzde makine öğrenmesi yöntemlerinin kullanılması, kanser hastalığının erken teşhisi ve tahmini için yapılan çalışmalara büyük katkılar sağlamaktadır. Bu çalışmada da k-En Yakın Komşu, Destek Vektör Makinaları, Naive Bayes, Karar ağaçları ve Yapay Sinir Ağları gibi beş farklı makine öğrenmesi yöntemleri Kaggle platformunda yer alan iki farklı göğüs kanseri veri kümesi üzerinde uygulanmıştır. Elde edilen sonuçlar doğruluk değerleri ve karmaşıklık matrisi değerleri ile verilerek karşılaştırılmıştır. Birinci göğüs kanseri veri kümesi içinde %98,2456 doğruluk oranıyla ve ikinci göğüs kanseri veri kümesinde %93,8596 doğruluk oranıyla Yapay Sinir Ağları (YSA) yönteminde en yüksek doğruluk değerleri elde edilmiştir. ',
                                category:'Gögüs Kanseri Veri Seti Analizi' } ,
                                { id:9, 
                                    name:"Göğüs Kanseri Verileri Üzerinde Makine Öğrenmesi Yöntemlerinin Uygulanması", 
                                    imageUrl:'9.jpg', 
                                    description:'Kanser dünya genelinde pek çok insanın ölümüne sebep olan en önemli hastalıklardan biridir. Özellikle göğüs kanseri kadınlar arasında en çok rastlanan hastalıkların başında yer almaktadır. Bu sebeple kanser hastalığının teşhisi ile alakalı herhangi bir gelişme insanların sağlıklı bir yaşam sürmesi açısından oldukça önemlidir. Günümüzde makine öğrenmesi yöntemlerinin kullanılması, kanser hastalığının erken teşhisi ve tahmini için yapılan çalışmalara büyük katkılar sağlamaktadır. Bu çalışmada da k-En Yakın Komşu, Destek Vektör Makinaları, Naive Bayes, Karar ağaçları ve Yapay Sinir Ağları gibi beş farklı makine öğrenmesi yöntemleri Kaggle platformunda yer alan iki farklı göğüs kanseri veri kümesi üzerinde uygulanmıştır. Elde edilen sonuçlar doğruluk değerleri ve karmaşıklık matrisi değerleri ile verilerek karşılaştırılmıştır. Birinci göğüs kanseri veri kümesi içinde %98,2456 doğruluk oranıyla ve ikinci göğüs kanseri veri kümesinde %93,8596 doğruluk oranıyla Yapay Sinir Ağları (YSA) yönteminde en yüksek doğruluk değerleri elde edilmiştir. ',
                                    category:'Gögüs Kanseri Veri Seti Analizi' } ,
                        
                    
                      ],
        categories: [
            {id: 1, name: "Veri Madenciliği"},
            {id: 2, name: "Veri Madenciliğinde Tıp Yöntemleri"},
            {id: 3, name: "Gögüs Kanseri Veri Seti Analizi"}
        ],
        orders:[]
    }
}